import "./globals.css";
import {ClerkProvider,SignInButton,SignUpButton,SignedIn,SignedOut,UserButton,} from '@clerk/nextjs'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>{children}
          <header className="w-screen bg-neutral-900 flex justify-end p-5 gap-5">
            <SignedOut>
              <SignInButton/>
              <SignUpButton>
                <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton/>
            </SignedIn>
          </header>
        </body>
      </html>
    </ClerkProvider>
  );
}
